rtCamp/godam

admin/godam-transcoder-functions.php, assets/src/css/admin.scss, assets/src/js/media-library/transcoding-status.js, assets/src/js/media-library/views/attachment.js
Fix the error occuring in the list view for the wp upload.
=> Fix the wp upload error for the list view [develop]

assets/src/js/video-analytics.js, inc/classes/class-media-library-ajax.php
1. Set Interval to check for Video ID before fetching analytics data.
2. Send Delete request to server when attachment is deleted.
=> Fix: Fetch Analytics

README.md, readme.txt
- Tested up to: 6.7.2
- Added all supported audio and video formats
Next release onwards, changelog will be added to changelog.md file.
=> Update README.md and readme.txt with all supported formats

pages/video-editor/components/appearance/Appearance.js
Removes setting to adjust control bar orientation
=> Remove control bar position setting

admin/godam-transcoder-functions.php, assets/src/blocks/godam-player/video-analytics-plugin.js, assets/src/css/admin.scss, godam.php, inc/classes/class-easydam-constants.php, inc/classes/class-pages.php, inc/classes/rest-api/class-analytics.php, pages/analytics/Analytics.js, pages/analytics/Tooltip.js, pages/analytics/index.scss
- Banner and Tooltips updated for Analytics page
- Updated Godam Analytics Endpoint Base Constant
By default: `GODAM_ANALYTICS_BASE = https://analytics.godam.io`
Please add this to wp-config in local setup:
```
define( 'GODAM_ANALYTICS_BASE', 'https://analytics.godam.rt.gw' );
```
=> Analytics UI and Endpoint Update

assets/src/js/media-library/transcoding-status.js, assets/src/js/media-library/transcoding-status/grid-view-transcoding-status.js
- reAttach events based on the uploading new attachments.
=> feat: reattach events based on the uploader status update

admin/godam-transcoder-admin.php, admin/godam-transcoder-handler.php, assets/src/css/admin.scss
=> Admin Dashboard Notices

inc/classes/class-media-library-ajax.php
- for `media-folder` taxonomy delete the child terms when parent term is deleted.
=> Remove the child term when parent term is deleted [develop]

assets/src/blocks/godam-player/edit.js, pages/analytics/Analytics.js
ref: https://github.com/rtCamp/godam/pull/172/files
=> Revert the poster-image changes

assets/src/css/admin.scss
- media library branding color should not show
=> fix: media library branding color should not show [develop]

assets/src/blocks/godam-player/edit.js, assets/src/blocks/godam-player/frontend.js, assets/src/blocks/godam-player/render.php, pages/analytics/Analytics.js
Select the video poster image dynamically
Here is the poster image priority
1. poster image from block editor if uploaded any
2. poster image selected from godam thumbnail selector
3. image save in wordpress meatadata
=> improve godam/video block

assets/src/css/media-library.scss, assets/src/js/media-library/index.js, assets/src/js/media-library/utility.js, assets/src/js/media-library/views/attachment-browser.js, assets/src/js/media-library/views/attachment.js, inc/classes/class-assets.php, inc/classes/rest-api/class-settings.php, pages/godam/GeneralSettings.js
=> Add Toggle button to disable DAM functionalities [develop]

inc/classes/class-media-library-ajax.php, pages/media-library/App.js, pages/media-library/components/modal/DeleteModal.jsx, pages/media-library/components/modal/FolderCreationModal.jsx, pages/media-library/components/modal/RenameModal.jsx, pages/media-library/components/modal/scss/modal.scss, pages/media-library/redux/middleware/localstorage.js, pages/media-library/redux/slice/folders.js
- Fix the selectedFolder being taken from the localStorage instead of the URI.
- Child terms not being selected issue resolution.
- Stacking context of the media modal resolution
Form the doc: https://docs.google.com/document/d/1GGTedNi5_9mCjqq-jQ1-fqVshs9DyEFrYC8RIMZY4KM/edit?tab=t.6y4uj5x9sihx
=> DAM feature related QA issue solutions.

inc/classes/class-deactivation.php, webpack.config.js
- fix deactivation script JS issue
=> feat: add build deactivation script [develop]

readme.txt
feat: Add youtube embed link in readme.txt (#197)
=> Sync develop with master branch

composer.json, composer.lock, readme.txt
Remove the unused `aws/aws-sdk-php` package form composer to reduce the plugin zip file.
=> Remove the aws composer package from and update readme.txt

admin/godam-retranscode-admin.php, admin/godam-transcoder-handler.php, assets/src/blocks/godam-player/render.php, assets/src/js/admin.js, assets/src/js/media-library/views/attachment-detail-two-column.js, assets/src/js/media-library/views/filters/media-retranscode.js, assets/src/js/media-library/views/filters/media-upload-to-s3.js, assets/src/js/video-analytics.js, inc/classes/class-assets.php, pages/analytics/Analytics.js, pages/godam/App.js, pages/godam/GeneralSettings.js, pages/godam/redux/api/storage.js, pages/media-library/redux/api/folders.js, pages/video-editor/VideoEditor.js, pages/video-editor/components/cta/ImageCTA.js, pages/video-editor/components/layers/CTALayer.js, pages/video-editor/components/layers/FormLayer.js, pages/video-editor/redux/api/video.js, plugin-build.sh
- Update the use of REST API URLs across the plugin to support WordPress multisite
- Fix the retranscode bulk action for multisite setup
=> Add multisite plugin support

admin/godam-retranscode-admin.php, admin/godam-transcoder-handler.php, assets/src/blocks/godam-player/render.php, assets/src/js/admin.js, assets/src/js/media-library/views/attachment-detail-two-column.js, assets/src/js/media-library/views/filters/media-retranscode.js, assets/src/js/media-library/views/filters/media-upload-to-s3.js, assets/src/js/video-analytics.js, inc/classes/class-assets.php, pages/analytics/Analytics.js, pages/godam/App.js, pages/godam/GeneralSettings.js, pages/godam/redux/api/storage.js, pages/media-library/redux/api/folders.js, pages/video-editor/VideoEditor.js, pages/video-editor/components/cta/ImageCTA.js, pages/video-editor/components/layers/CTALayer.js, pages/video-editor/components/layers/FormLayer.js, pages/video-editor/redux/api/video.js, plugin-build.sh
ref: [PR](https://github.com/rtCamp/godam/pull/207)
=> Sync develop with master

assets/src/blocks/godam-player/VideoJS.js, assets/src/blocks/godam-player/block.json, assets/src/blocks/godam-player/edit.js, assets/src/blocks/godam-player/frontend.js, assets/src/blocks/godam-player/render.php, assets/src/blocks/godam-player/style.scss, pages/godam/VideoSettings.js
- Remove the ABS toggle button from the video setting page.
- Calculate the video aspect ratio and apply the styles on the godam video player to eliminate the **Cumulative Layout Shift** issue.
- Add border and shadow support style support on GoDAM/video block.
=> Remove ABS toggle button and minor changes

composer.json, composer.lock
This PR updates the coding standards to align the local PHPCS setup with the bot’s PHPCS configuration, ensuring consistency across development and automated checks.
**After merging this PR, all contributors should update their local PHPCS configurations to match these new standards. 🚀**
=> Update WordPress Coding standards

admin/godam-transcoder-functions.php, godam.php, inc/classes/class-media-library-ajax.php, inc/helpers/custom-functions.php
- Fix the `wp_unslash` issue for the plugin.
=> Fix some plugin check issues [master]

pages/godam/VideoSettings.js, pages/video-editor/VideoEditor.js, pages/video-editor/components/appearance/Appearance.js, pages/video-editor/components/cta/TextCTA.js
Fixes issues:
1. TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.: On toggling branding to true the first time
2. Volume always auto turnoff when you try to turn them on in video editor
3. In the text CTA, custom color for the individual text element is not applied on the front-end.
4. When making the video full screen and CTA text turns white
5. For low quality videos, show message to user indicating that video quality settings option will not be visible. It is not being shown for some poor quality videos that are transcoded.
6. Remove zoom level appearance setting
=> Fixes for minor issues

assets/src/js/media-library/views/filters/media-date-range-filter.js, inc/classes/class-media-library-ajax.php
- fix the issue where the attachment uploaded today does not show up on the list.
=> Fix the date range issue [master]

assets/src/blocks/godam-player/block.json, assets/src/blocks/godam-player/caption.js, assets/src/blocks/godam-player/edit.js, assets/src/blocks/godam-player/render.php, assets/src/blocks/godam-player/style.scss, inc/classes/rest-api/class-ads.php
- The caption will be automatically assigned from attachment data.
- The user can modify and remove the caption.
=> Feat: Implement GoDAM video caption support

admin/class-rtgodam-retranscodemedia.php, admin/class-rtgodam-transcoder-admin.php, admin/class-rtgodam-transcoder-handler.php, admin/class-rtgodam-transcoder-rest-routes.php, admin/godam-transcoder-functions.php, assets/src/blocks/godam-player/frontend.js, assets/src/js/media-library/utility.js, assets/src/js/media-library/views/attachment-browser.js, assets/src/js/media-library/views/attachment.js, assets/src/js/video-analytics.js, inc/classes/class-assets.php, inc/classes/class-media-library-ajax.php, inc/classes/class-pages.php, inc/classes/rest-api/class-analytics.php, inc/classes/rest-api/class-media-library.php, inc/classes/rest-api/class-settings.php, inc/helpers/custom-functions.php, pages/analytics/Analytics.js, pages/analytics/index.scss, pages/godam/App.js, pages/godam/GodamHeader.js, pages/godam/VideoSettings.js, pages/godam/index.scss, pages/video-editor/components/SidebarLayers.js, pages/video-editor/components/ads/CustomAdSettings.js, pages/video-editor/components/appearance/Appearance.js, pages/video-editor/components/layers/FormLayer.js, pages/video-editor/components/layers/HotspotLayer.js
This update removes all references to "license key" across the codebase and replaces them with "API key" or a similar term where appropriate. The changes ensure consistency and eliminate any mention of license keys.
- Renamed variables to reflect "API key" instead of "license key"
- Updated REST API endpoints to align with the new terminology
- Revised comments to remove references to license keys
=> Replace license variable to the API variable [master]

admin/class-rtgodam-transcoder-rest-routes.php
- Use `upload_files` permission for media transcoding API call
=> Add permission callback for media transcoder api call

admin/godam-transcoder-functions.php, inc/classes/class-media-library-ajax.php
- Add the nonce check for the `add_attachment` function.
- remove the else condition from the variable sanitization function.
=> Some review changes for the master branch [master]

pages/video-editor/VideoEditor.js
- Fix the issue where sources of the video were not getting set.
=> Video editor fatal error when loading the video [develop]

readme.txt
This pull request includes changes to the `readme.txt` file to improve the formatting and readability of the FAQ section. The main change is the modification of the question headers to a more consistent and visually appealing format.
Changes to FAQ section formatting:
* [`readme.txt`](diffhunk://#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6L99-R125): Updated the question headers in the FAQ section to use a consistent format with surrounding equal signs for better readability.
=> Update the FAQ section of the reame.txt file

pages/media-library/components/modal/DeleteModal.jsx, pages/media-library/components/modal/FolderCreationModal.jsx, pages/media-library/components/modal/RenameModal.jsx
**Improved accessibility and user experience across all modal components by:**
- Adding `useRef` and `useEffect` to auto-focus relevant elements (input fields or buttons) when modals open.
- Implement `handleKeyDown` to submit forms via the Enter key (with validation for non-empty input where applicable).
- Replacing `ButtonGroup` with a `div` for button layout consistency.
**Affected components:**
- `DeleteModal.jsx`
- `FolderCreationModal.jsx`
- `RenameModal.jsx`
=> Enhance focus handling and refactor button group in modal Component

README.md, composer.json, godam.php, package.json, readme.txt
This pull request includes version updates and a new changelog entry for the GoDAM plugin. 
Version updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L13-R13): Updated the stable tag to version 1.0.2.
* [`godam.php`](diffhunk://#diff-11ad0cbfc6e1732b964b5298a09e2b1cd2df3efc7f60babe88d5d0e88d748916L6-R6): Updated the plugin version to 1.0.2. [[1]](diffhunk://#diff-11ad0cbfc6e1732b964b5298a09e2b1cd2df3efc7f60babe88d5d0e88d748916L6-R6) [[2]](diffhunk://#diff-11ad0cbfc6e1732b964b5298a09e2b1cd2df3efc7f60babe88d5d0e88d748916L44-R44)
* [`readme.txt`](diffhunk://#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6L7-R7): Updated the stable tag to version 1.0.2.
Changelog entry:
* …
=> Update version number to 1.0.2 in plugin files and README [main]

README.md
This pull request adds a link to the `README.md` file for suggesting new features, improving user engagement and feedback collection.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R233-R234): Added a link to the GitHub Discussions feature requests category to allow users to suggest new features.
=> docs: add link to GitHub Discussions for feature requests in README

README.md, godam.php, readme.txt
- Fix: Video player ads related console errors, and add optional chaining to avoid console errors.
- Fix: Addressed an edge case where users couldn't save a new API key if the previous one had expired.
- Fix: Update the settings page links and wordings.
- Feat: Improve the GoDAM video player UI.
- Feat: Enabled the watermark feature for users on the Starter plan.
=> Update the plugin version and add changelog

assets/src/blocks/godam-audio/block.json, assets/src/blocks/godam-audio/caption.js, assets/src/blocks/godam-audio/edit.js, assets/src/blocks/godam-audio/editor.scss, assets/src/blocks/godam-audio/index.js, assets/src/blocks/godam-audio/render.php, assets/src/blocks/godam-audio/save.js, assets/src/blocks/godam-audio/style.scss, assets/src/blocks/godam-audio/theme.scss, assets/src/utils/init-block.js, inc/classes/class-blocks.php
Resolves Issue #289 
GoDAM Audio Block created with the following features:
1. CDN URL with a fallback of attachment URL
2. Responsiveness, flexible width
3. Autoplay
4. Loop
5. Download option
6. Playback speed
7. Caption
https://github.com/user-attachments/assets/e0003d9d-011e-4dbc-8200-4d44d036f854
=> GH-289 Implement GoDAM Audio Block for CDN-Hosted Audio Playback

admin/class-rtgodam-transcoder-handler.php, admin/class-rtgodam-transcoder-rest-routes.php, assets/src/js/media-library/transcoding-status/grid-view-transcoding-status.js, assets/src/js/media-library/transcoding-status/list-view-transcoding-status.js, inc/classes/class-media-tracker.php, inc/classes/class-plugin.php
- Add admin notice when CDN conflict is detected with GoDAM transcoding service.
- Remove the email notification on video transcoding failure.
=> Add admin notice when CDN conflict detected with GoDAM transcoding service.

pages/video-editor/VideoEditor.js, pages/video-editor/components/SidebarLayers.js, pages/video-editor/components/forms/CF7.js, pages/video-editor/components/forms/GravityForm.js, pages/video-editor/components/forms/WPForm.js, pages/video-editor/components/forms/fetchForms.js, pages/video-editor/components/layers/FormLayer.js, pages/video-editor/redux/slice/videoSlice.js
Check if WPForms and CF7 plugins are active and display the form layers and controls.
=> Add the plugin activation logic and disable the layer field if respective plugin is not active

README.md, admin/class-rtgodam-retranscodemedia.php, admin/class-rtgodam-transcoder-handler.php, assets/src/blocks/godam-player/style.scss, assets/src/js/media-library/transcoding-status.js, inc/helpers/custom-functions.php, languages/godam.pot, pages/media-library/redux/api/folders.js, pages/video-editor/components/appearance/Appearance.js, pages/video-editor/components/layers/CTALayer.js, pages/video-editor/video-control.css, readme.txt
This PR fixes the following [issues](https://docs.google.com/document/d/1KDpp3WxD6g8c0_J-p9SR5PzO148xZbgF3V97gyMmWOs/edit?addon_store&tab=t.mxtdl5q8o7l):
- Transcoding status shown wrong
- Folder creation issues in Media Library
- Unknown Failure reason is shown when media type : audio is re-transcoded
- Button not visible on FE for CTA : Image
Also updated README tags and links in readme.txt and README.md files.
=> Fixed QA Issues - 1

webpack.config.js
Fixes error:
Module not found: Error: Can't resolve '/github/workspace/assets/src/js/video-analytics.js' in '/github/workspace'
resolve '/github/workspace/assets/src/js/video-analytics.js' in '/github/workspace'
=> Fix build error

admin/class-rtgodam-transcoder-handler.php, admin/godam-transcoder-actions.php
This pull request introduces enhancements to handle video thumbnails more effectively, particularly for media managed by the `RTMediaModel`. Key changes include adding functionality to update metadata and cover art for video thumbnails.
=> Make thumbnails compatible with rtmedia gallary view

README.md, godam.php, package.json, readme.txt
- **Fix**: Updated plugin to support translations and localization.
- **Enhancement**: Added compatibility for displaying thumbnails in the rtMedia gallery view.
=> docs: Update versions for Release 1.0.5

.github/workflows/release_on_tag.yml
=> Revert "Add PHP setup and POT file generation steps to release workflow"

pages/analytics/Analytics.js, pages/analytics/charts.js, pages/analytics/index.scss
1. Disable analytics page on mobile
2. Convert watch time display to human-readable format
=> Fixes to Analytics Frontend

assets/src/blocks/godam-player/frontend.js, assets/src/blocks/godam-player/style.scss
Updates style for share button:
Desktop:
Mobile:
=> Fix share button style

assets/src/js/godam-player/frontend.js, inc/templates/godam-player.php, pages/video-editor/components/ads/CustomAdSettings.js
1. Add url validation with debounce in ad url input field
https://github.com/user-attachments/assets/33675da4-46f7-42f6-961e-e4044f79ee71
updated error message
2. Prevent autoscroll after form submission in WPForms and Gravity Forms
https://github.com/user-attachments/assets/fb49ac5f-ea4c-427b-ba44-4ceb68848e3e
=> Fix autoscroll in form submission + add url validation in ad url

inc/classes/class-media-library-ajax.php
- Implement logic to upload images on GoDAM server.
=> Implement logic to upload images on GoDAM server

inc/classes/class-media-library-ajax.php
Add image extension name after image file name when upload the image file on GoDAM server
=> Add image extension at then end of image file name

inc/classes/rest-api/class-analytics.php, inc/classes/rest-api/class-cf7.php, inc/classes/rest-api/class-gf.php, inc/classes/rest-api/class-media-library.php, inc/classes/rest-api/class-polls.php, inc/classes/rest-api/class-settings.php, inc/classes/rest-api/class-transcoding.php, inc/classes/rest-api/class-wpforms.php
This PR prepares strings under the `inc/classes` directory ready for translation.
Closes #373
=> enhance: prepare strings in the inc/classes directory ready for translation

inc/classes/shortcodes/class-godam-player.php, inc/templates/godam-player.php
1. Fix error while displaying modal by localizing script with correct variable
2. Fix condition to render share button so it only renders for trancoded videos
=> Fix share button render conditions and error

pages/video-editor/VideoEditor.js, pages/video-editor/attachment-picker.scss
Description:
1. This commit adds an aspect ratio to the video player.
2. Updates the max-width for the canvas parent element as per the screen size.
| Before | After |
|---|---|
| ![Image](https://github.com/user-attachments/assets/9f253d53-a1dc-42c3-8740-5969bc7fae55) | ![Image](https://github.com/user-attachments/assets/deb626e4-7cf8-4a2b-8927-66fa50e50f75) |
=> Fix: Video editor for vertical layout videos

admin/class-rtgodam-retranscodemedia.php, admin/godam-transcoder-functions.php, assets/src/js/godam-player/frontend.js, assets/src/js/media-library/transcoding-status/transcoding-checker.js, assets/src/js/media-library/views/attachment.js, inc/classes/class-media-library-ajax.php, inc/classes/rest-api/class-transcoding.php, pages/video-editor/VideoEditor.js, pages/video-editor/components/SidebarLayers.js
Resolves #354 
- Show transcoding status for Retranscoding videos
- Fix: "Check Status" button not working in Media Library list view
- When we click on Add Layer then the video should pause if playing.
- In polls layer if "Allow User to Skip" is disabled, users can get stuck. Add continue button.
=> Fix Phase 2 Bugs

assets/src/css/godam-player.scss, assets/src/js/godam-player/chapters.js, inc/classes/shortcodes/class-godam-player.php, pages/godam/components/VideoCustomCSSTemplate.js, pages/godam/components/tabs/VideoSettings/CustomVideoPlayerCSS.jsx, pages/godam/redux/slice/media-settings.js, pages/video-editor/VideoJSPlayer.js, pages/video-editor/components/chapters/Chapters.js, pages/video-editor/style.scss
1.  Replace “layer” keyword with chapter
2. Fix null offset error for custom css setting access
3. Improvements to skin CSS editor
4. Allow user to view previous chapter even if the control bar has already seeked them
5. Replace time format instruction
=> Fixes for feedback of Skins and Custom CSS

assets/src/blocks/godam-player/block.json, assets/src/blocks/godam-player/edit.js, assets/src/css/godam-gallery.scss, assets/src/css/godam-player.scss, assets/src/js/godam-player/frontend.js, inc/templates/godam-player.php
This PR adds a Time Range picker for the user to select the amount of time the Block Overlay will be visible.
Also fixes:
1. Z-index issue
2. Share button and modal cross button overlap
3. Share Modal Close functionality
=> Block Overlay - Time Range selection option

README.md, assets/src/blocks/godam-player/edit.js, assets/src/css/godam-player.scss, assets/src/js/godam-player/frontend.js, inc/classes/class-elementor-widgets.php, inc/classes/class-seo.php, pages/video-editor/components/ads/CustomAdSettings.js, readme.txt
- Fix the video player quality, and speed menu z-index issue.
- Add bottom margin after custom video ad selector field.
- Add aspectRation `16:9` option on video player block editor page.
- Reposition the video caption control on mobile device to avoid overlap with video settings button
**Bug**
**Solution**
=> Fix video player minor style issues

admin/class-rtgodam-transcoder-rest-routes.php, inc/classes/rest-api/class-transcoding.php
This PR adds updates for callback endpoints:
```
/wp-json/godam/v1/transcoder-callback
/wp-json/godam/v1/transcoding/transcoding-status
```
=> GH 246 Fix: Update on callback endpoints

pages/godam/components/godam-footer.scss, pages/godam/index.scss
=> GH-535 Fix navigation links focus state.

pages/godam/components/tabs/GeneralSettings/BrandImageSelector.jsx, pages/godam/components/tabs/VideoSettings/VideoWatermark.jsx, pages/video-editor/components/appearance/Appearance.js, pages/video-editor/components/cta/ImageCTA.js
- Closes #510
---
- After a media item is selected, check the attachment type.
- If the selected file is **not an image**, exit early and do not set the media.
---
https://github.com/user-attachments/assets/2ffdf394-bfe1-4f22-bb72-6820ca6c6067
https://github.com/user-attachments/assets/d606d2cc-07b2-49dd-8261-083fa75bb094
=> GH 510: Fix godam video settings, layer to restrict images on upload files selection

README.md, readme.txt
This PR closes #573 by making several minor changes in the plugin's README file to make it more readable and SEO friendly.
=> GH-573 Improve Readability of README file

inc/classes/rest-api/class-media-library.php
closes #586 
Add backward compatibility for thumbnail URLs.
=> GH 586: Fix thumbnail links backward compatibility

pages/media-library/index.scss
part of #287 
Fix Snackbar toast height bug
=> Fix: Snackbar toast height

admin/class-rtgodam-transcoder-handler.php
* fix: restore rtMedia thumbnail support
* docs: update rtMedia support comment
=> Fix: Restore thumbnails for rtMedia (#650)

assets/src/js/media-library/index.js, assets/src/js/media-library/models/attachments.js
part of #287 
Fix sidebar now showing up in list view.
Know issue:
Hide sidebar button does not show up in list view
=> Fix: List view sidebar not showing

assets/src/blocks/godam-player/block.json, assets/src/blocks/godam-player/edit.js, assets/src/css/godam-player.scss, inc/templates/godam-player.php
Hover effect for the play icon
Also corrected the automatic formatting for the file.
https://github.com/user-attachments/assets/d6041f8b-1c22-4598-a546-f512d7b4cb66
=> Hover effect for playicon for the GoDAM Player [develop]

pages/video-editor/components/forms/CF7.js, pages/video-editor/components/forms/EverestForm.js, pages/video-editor/components/forms/FluentForm.js, pages/video-editor/components/forms/GravityForm.js, pages/video-editor/components/forms/JetpackForm.js, pages/video-editor/components/forms/Sureform.js, pages/video-editor/components/forms/WPForm.js, pages/video-editor/components/forms/fetchForms.js, pages/video-editor/components/forms/forminatorForms.js, pages/video-editor/components/layers/FormLayer.js
- Closes - #666 
https://github.com/user-attachments/assets/e4d91571-d15a-4d9c-b3fe-c837239510d3
https://github.com/user-attachments/assets/4acd3a6a-bd53-482a-8437-b47af71ba9b3
=> GH Issue - 666: Prevent unnecessary API calls to fetch forms and related forms data

pages/media-library/App.js, pages/media-library/components/modal/scss/modal.scss, pages/media-library/index.scss
Fix top menu bar spacing
Update styles for modals
=> Fix: Media library top menu bar spacing and modal buttons

.github/workflows/release_on_tag.yml
PR to add workflow to create ZIP file from develop on branch merge and dry-run tag
=> ci(release): update workflow to include develop branch for dry-run

assets/src/js/media-library/views/media-frame-select.js, inc/classes/class-video-metadata.php, pages/video-editor/components/LayerSelector.jsx
All these fixes are made in this PR:
- MPG video thumbnail not applied on video
- Select Featured Image from GoDAM Tab (Error fix)
- Add `All` tab in layer selector
=> Fix QA issues for 1.3.0

assets/src/js/admin.js, pages/analytics/Video.js, pages/video-editor/components/LayerSelector.jsx, pages/video-editor/components/layer-selector.scss
1. chore: Remove logs
2. fix: Reduce Poll layer label brightness
3. fix: Remove box shadow from layer selector tabs header
4. fix: Set 'all' tab active when searching in layer selector
=> Fix - QA Issues

assets/src/blocks/godam-player/style.scss, assets/src/css/_variables.scss, assets/src/css/godam-player.scss, assets/src/js/godam-player/frontend.js
- This PR adds functionality to control the visibility of a custom share button based on the user's interaction with the Video.js player and the playback state.
- Modifies CSS of the modal for better UI.
The built-in Video.js control bar visibility logic and related classes (.vjs-control-bar, .vjs-user-active, etc.) do not apply to our custom share button because:
- The share button is rendered outside the standard Video.js control bar.
- Video.js only applies visibility-related classes (vjs-user-active / vjs-user-inactive) to its own elements, not external DOM nodes.
**To test this feature, you can head to my website** - [Live Working](https://anuj-singh.rt.gw/?godam_page=video-preview&id=15)
https://github.com/user-attachments/assets/e98db022-9a86-4911-8c89-c816170d637c
| Before | After …
=> Share button Visibility 

assets/src/blocks/godam-player/style.scss, assets/src/css/godam-player.scss
Adds variables module that contains shared css variable.
=> Import variables module to stylesheet

CONTRIBUTING.md
The `CONTRIBUTING.md` file is added as a guideline for contributions.
=> docs: Create new CONTRIBUTING.md file

pages/analytics/helper.js, pages/godam/components/GoDAMHeader.jsx
=> GH 721: Fix JS error on analytics page #721

pages/godam/App.js, pages/godam/components/tabs/VideoSettings/APISettings.jsx, pages/godam/index.scss, pages/tools/App.js, pages/tools/index.scss
> 1. Settings Page Mobile Layout Issues
https://github.com/user-attachments/assets/78d5ff45-82ef-4b3a-814c-7d49d57dc754
=> GH:733 - Improve settings/tools sidebar navigations

assets/src/blocks/godam-player/components/VideoSEOModal.js, assets/src/blocks/godam-player/edit.js, assets/src/blocks/godam-player/utils/index.js
This PR fixes the VideoSEO modal where default values were not saved for the VideoSEO.
=> VideoSEO fix where the SEO data does not appear

inc/classes/rest-api/class-video-migration.php
Core and Vimeo migration was using empty array for sources, relying on the editor to figure it out during runtime. This caused VideoJS errors causing the godam video block to not load sometimes. 
This PR fixes it by setting the sources during migration itself to prevent these errors.
=> fix: use correct sources array during migration

assets/src/js/media-library/utility.js, pages/media-library/components/search-bar/SearchBar.jsx
part of #784 
- Optimize folder search rendering
- fix hide folder button not showing up in editor (Bug in get settings function URL)
=> Fix: Media Folder search bug

assets/src/css/_common.scss, assets/src/css/admin.scss, assets/src/css/godam-player.scss, assets/src/js/woocommerce/admin/wc-add-to-product.js, assets/src/js/woocommerce/godam-product-gallery/modal.js, assets/src/js/woocommerce/godam-product-gallery/sidebar.js, inc/classes/woocommerce/class-wc-product-gallery-video-markup.php, inc/classes/woocommerce/class-wc-product-video-gallery.php
- Added a collapsible feature for opening and closing the sidebar.
- Shifted the mini cart to the right side of videos for better UI alignment.
- Introduced a video section in the "Add to Products" admin area to manage timestamps.
=> WooCommerce Integration: Sidebar Enhancements & Mini Cart UI Update

assets/src/blocks/godam-player/block.json, inc/templates/godam-player.php
Issue: https://github.com/rtCamp/godam/issues/673
This PR should resolve the share button not appearing for the video directly added from the GoDAM library.
=> Fix Share button not appearing on the video added directly from GoDAM

CONTRIBUTING.md, README.md, admin/godam-transcoder-functions.php, godam.php, inc/classes/class-video-permalinks.php, inc/classes/post-types/class-godam-video.php, languages/godam.pot, package-lock.json, package.json, readme.txt
1. Update the Stable tag in readme.txt
2. Update the Stable tag in README.md
3. Update the version in the godam.php file header
4. Update the version in the godam.php variable
5. Update the version in the package.json file (and then update the .pot file)
6. Update `@since n.e.x.t` to the actual release version
=> docs: Update plugin version to 1.3.1

pages/tools/components/tabs/Migration/CoreVideoMigration.jsx, pages/tools/components/tabs/Migration/MigrationTab.jsx, pages/tools/components/tabs/Migration/VimeoVideoMigration.jsx, pages/tools/index.scss
Updates the UI of migration tab in tools page according to the feedback received.
Before:
After:
cc: @subodhr258 @nayemDevs @pooja-muchandikar
=> Fix: Migration UI

assets/src/js/godam-player/frontend.js
=> Fix control bar shifting at top for full screen in Pills skin

pages/analytics/PlaybackPerformance.js, pages/analytics/SingleMetrics.js, pages/dashboard/Dashboard.js
https://github.com/user-attachments/assets/7895c80c-5000-4704-9fd6-868091eb1407
Fixes: #734
=> [GH-734] chore: Responsive dashboard page

inc/classes/class-plugin.php, inc/classes/class-video-editor-form-layer-handler.php, inc/classes/ninja-forms/class-ninja-forms-integration.php, inc/templates/render-video-editor-form-layer.php, pages/video-editor/components/forms/NinjaForm.js
This PR fixes `Ninja Form Renders on Video Editor Page Without Selecting a Form`.
https://github.com/user-attachments/assets/0f8f85ca-2ab5-4eba-9cec-066ea9087eb5
Closes - #853
=> fix: Ninja Form Renders on Video Editor Page Without Selecting a Form

assets/src/js/godam-player/masterSettings.js
Closes #823 
This PR improves the SettingsButton UX by:
- Adding attachOutsideClickListener() to close the menu when clicking outside.
- Cleaning up the listener in the dispose() method to prevent memory leaks.
- Ensuring the listener is attached when opening a submenu via openSubmenu().
Previously, the settings menu stayed open on outside clicks. This change ensures it closes properly.
https://github.com/user-attachments/assets/724fd71e-9264-4826-ba61-07a85ee02ffe
=> GH-823 Enhance Video Player Controls User Experience

assets/src/css/admin.scss, assets/src/css/media-library.scss, assets/src/js/media-library/views/attachment-detail-two-column.js
closes #884 
This PR fixes Button spacing on Media Library Page
Center Plus icon on thumbnail selection
=> Fix: Button spacing on media library page

inc/classes/rest-api/class-video-migration.php
**Issue:** #318 
- Add a custom hook to provide support for the custom Vimeo block migration during the GoDAM Vimeo migration process.
- Correct the attachments URLs and transcoded URLs metadata.
**Before migration**
**After Migration**
```php
<?php
/**
* Plugin Name: RT Blocks Migration Helper
* Description: Handles migration of RT Blocks to GoDAM blocks
* Version: 1.0.0
* Author: rtCamp
* Author URI: https://rtcamp.com
* Text Domain: rt-blocks-migration-helper
*/
defined( 'ABSPATH' ) || exit;
// Define a constant for debug mode
define('RT_BLOCKS_MIGRATION_DEBUG', true);
/**
* Class RT_Blocks_Migration_Helper
*/
class RT_Blocks_Migration_Helper {
/**
* Constructor
*/
public function __construct() {
add_filter( 'rtgodam_migrate_vimeo_block', array( $this, …
```
=> Custom hook to provide custom vimeo videos migration

assets/src/css/media-library.scss, assets/src/js/media-library/views/attachment-detail-two-column.js, inc/classes/rest-api/class-media-library.php
Resolves issue: https://github.com/rtCamp/godam/issues/713#issuecomment-3166627461
1. When the maximum allowed number of thumbnails is uploaded and the currently selected thumbnail is deleted, the default thumbnail is auto-selected.
2. After selecting a thumbnail from the uploaded images, the change is reflected immediately in the media library grid view as well as single video
3. Fix media library sidebar height issue
=> Fix QA issues for Custom Thumbnail Upload

CHANGELOG.md, readme.txt
Add change log for HLS url support
=> Add changelog for HLS support for GoDAM Virtual Media

pages/tools/components/tabs/RetranscodeTab.jsx
This pull request refactors the error and status notification system in the `RetranscodeTab` component to use the `Notice` component instead of `Snackbar`, consolidates all status messages into a single, centralized notice state, and improves user feedback throughout the retranscoding workflow.
**Notifications and User Feedback Improvements:**
* Replaced all instances of the `Snackbar` component with the `Notice` component for displaying status and error messages in `RetranscodeTab.jsx`, and refactored the notification logic to use a centralized `notice` state. [[1]](diffhunk://#diff-127e7446d128bc2c4ed75e0b2af4d1152fa3d977361ad7c2a1b1e385e3745d83L13-L23) [[2]](diffhunk://#diff-127e7446d128bc2c4ed75e0b2af4d1152fa3d977361ad7c2a1b1e385e3745d83R36) …
=> fix: update retranscoding UI to use notices instead of snackbars

admin/godam-transcoder-functions.php
This pull request updates the API key verification logic in `admin/godam-transcoder-functions.php` to improve error messaging and provide additional site information during verification. The main changes are focused on enhancing the request sent to the API.
API key verification improvements:
* The API request body now includes the site title (retrieved from WordPress options via `get_bloginfo('name')`), providing more context about the site during API key verification.
=> GH-392 Fix Active Sites list

pages/video-editor/components/SidebarLayers.js, pages/video-editor/components/layers/HotspotLayer.js, pages/video-editor/components/layers/LayersHeader.js, pages/video-editor/redux/slice/videoSlice.js
Reverts rtCamp/godam#977 as it is not a part of 1.4.0 release.
=> Revert "Feat: Editable layers and hotspot names"

assets/src/css/admin.scss, assets/src/css/media-library.scss
=> Fix: Attachment Details button styles

assets/src/js/godam-player/godam-player-sdk.js
This PR makes use of externally controlled variable in string, to prevent accidental formatting interpretation if variable contains format specifiers.
=> FIX: Vulnerable logging in Player SDK

assets/src/js/godam-player/managers/menuButtonHover.js
Fixes issue: https://github.com/rtCamp/godam/issues/942#issuecomment-3243123434
https://github.com/user-attachments/assets/ba03163f-f62c-4747-aebc-d43b14a6229d
=> Prevent opening of multiple control bar menus

inc/classes/class-video-engagement.php
Description:
Enable engagement bar only for transcoded video.
=> Fix: Enable engagements for transcoded videos only checked by rtgodam_transcoding_status

CHANGELOG.md, README.md, godam.php, inc/helpers/custom-functions.php, languages/godam.pot, package-lock.json, package.json, readme.txt
- Tweak: Enhanced Audio Recording support in GoDAM Recorder for Gravity Forms
- Fix: Video player UI bugs and playback quality issues
- Fix: Analytics tracking for dynamically rendered videos
=> docs: Update changelog and version to 1.4.1
