rtCamp/godam

- assets/src/blocks/godam-player/render.php
- inc/classes/rest-api/class-ads.php
- pages/video-editor/VideoEditor.js
- pages/video-editor/redux/slice/videoSlice.js
- Fix the empty ad tag url issue.
- Remove the tracking of ad events, as no analytics endpoint is handling it.
> Fix the self-hosted ad empty URL, and remove the ads event tracking

- godam.php
- inc/classes/class-pages.php
- pages/analytics/Analytics.js
- pages/analytics/index.scss
- Added a link that redirects to General Settings page from Analytics page, to activate license.
- Changed Plugin Name in main plugin file from GoDAM to DAM
> Analytics Redirect and Plugin Name change

- admin/godam-transcoder-actions.php
- admin/godam-transcoder-handler.php
- godam.php
- inc/classes/class-cron.php
- inc/classes/class-plugin.php
- pages/godam/VideoSettings.js
1. Created CRON job to delete Transcoded CDN URLs for all videos when the 30-day grace period after license expiry is exceeded. Also unscheduled the event when plugin is deactivated. 
2. Updated Transcoded CDN URL for Non-ABS videos as well.
3. Updated Post MIME Type for all videos to mp4 to fix video playback issue.
4. Adjusted Video Resolution values in Video settings.
> Transcoding URL changes

- assets/src/blocks/godam-player/VideoJS.js
- assets/src/blocks/godam-player/frontend.js
- assets/src/blocks/godam-player/render.php
- assets/src/blocks/godam-player/style.scss
- inc/classes/class-assets.php
- package-lock.json
- package.json
- plugin-build.sh
This PR introduces **video thumbnail sprite** support to enhance the video hover preview experience. The following key updates have been implemented:  
- The **sprite image URL** is dynamically generated based on the video source.  
- The filename (whether `.mpd` or `.mp4`) is replaced with `sprite.png`.  
- Added logic to **fetch and display sprite thumbnails** at predefined intervals of 10 seconds.  
- Static **thumbnail dimensions**:  
- **Width:** `320px`  
- **Height:** `180px` (static, maintaining 16:9 aspect ratio).  
- When setting up the video source:  
- If the **transcoded URL ends with `.mp4`**, assign `type: video/mp4`.  
- Otherwise, keep the default `type: application/dash+xml`.  
This is done, as currently the type for transcoded url is set to `type: application/dash+xml`, …
> Add preview thumbnail feature

- phpcs.xml
Refer https://github.com/WordPress/WordPress-Coding-Standards/blob/38168bc542ec3565c04f2a88498a2024cdfd9ba1/CHANGELOG.md?plain=1#L261
> update: update `WordPress.PHP.DisallowShortTernary` to `Universal.Operators.DisallowShortTernary` in phpcs.xml

- .github/hosts.yml
- .github/workflows/deploy_on_push.yml
This pull request includes changes to update branch references from `master` to `main` in configuration files.
Branch reference updates:
* [`.github/hosts.yml`](diffhunk://#diff-793eb4471e1092126a5ab929b14fee9b2567346f5255f968b9c354c7c63dfb0dL1-R1): Changed the branch reference from `master` to `main`.
* [`.github/workflows/deploy_on_push.yml`](diffhunk://#diff-044e2a519ecdf2d11c1895357aa1cc256ad3bf9063b1bf622dd860b664c17b3cL4-R4): Updated the branch reference from `master` to `main` under the `push` event.
> Update branch references from master to main

- .gitignore
- assets/src/blocks/godam-player/render.php
- pages/video-editor/redux/slice/videoSlice.js
**Issue:** Ad server and self-hosted ads are not loading properly because of the wrong conditional logic used to render ads.
**Solution:** Set the default adServer value and fix the condition to render ads.
> Fix the conditional logic to load ad server and self-hosted ads

- assets/src/blocks/godam-player/frontend.js
Add default video controls, if not added by `Video Editor > Player Settings`
> Add default controls for video player if not set from video-editor page

- pages/analytics/Analytics.js
1. Fix special characters in title
2. Prevent rendering duration if not available
Before:
After:
> Minor fixes to single analytics screen

- .github/workflows/release_on_tag.yml
This pull request updates the `.github/workflows/release_on_tag.yml` file to enhance the release process by adding steps for setting up PHP and generating a POT file.
Enhancements to the release workflow:
* Added a step to set up PHP 8.4 with Composer v2 using the `shivammathur/setup-php@v2` action.
* Included a step to generate a POT file by running `composer run pot` with a Bash shell.
> Add PHP setup and POT file generation steps to release workflow

- assets/src/blocks/godam-player/edit.js
- pages/video-editor/App.js
This pull request refactors the `VideoEdit` component in `godam-player` to improve code readability and maintainability by restructuring `BaseControl` usage. Additionally, it updates a CSS import in the `video-editor` app to align with the project's file structure.
* Replaced `BaseControl.VisualLabel` with `BaseControl` components for better semantic structure and consistent styling:
- Added `BaseControl` for the "Poster image" section, moving the label directly into the control.
- Added `BaseControl` for the "Customise Video" section, replacing the previous `div` wrapper.
- Added `BaseControl` for the "SEO Settings" section, improving consistency with other controls. [[1]](diffhunk://#diff-7f3eed49285d53dd5ca33b2e1543d8964dcce2aa03553b162df3c1a9068dfa66L396-R407) …
> Fix the breaking styles for video block and video-editor

- assets/src/css/_common.scss
- assets/src/css/media-library.scss
- assets/src/js/media-library/utility.js
- pages/godam/components/GoDAMHeader.jsx
- Disable to the "Manage media" button if user license is not active
> Disable the manage media button instead of hide

- inc/classes/rest-api/class-settings.php
- inc/classes/shortcodes/class-godam-player.php
- pages/godam/App.js
- pages/godam/components/tabs/VideoSettings/CustomVideoPlayerCSS.jsx
- pages/godam/components/tabs/VideoSettings/VideoPlayer.jsx
- pages/godam/redux/slice/media-settings.js
1. Add “Video Player” Settings Page for Custom CSS Injection
This PR introduces a new **"Video Player"** settings menu in the WordPress admin dashboard, allowing users to input **custom CSS** specifically for styling the **GoDAM video block** globally on the frontend.
* Adds a new submenu item under the GoDAM plugin menu titled **"Video Player"**.
* Implements a settings page with a **code editor input** for custom CSS.
* Saves the entered CSS to the **WordPress options table**.
* Injects the saved CSS into the frontend, ensuring it applies globally to all GoDAM video blocks.
2. Provides a hook-based system `godam_player_enqueue_styles` that developers can also use to enqueue their own player-specific styles.
Example for usage:
```
add_action( 'godam_player_enqueue_styles', function () { …
```
> Settings to add custom CSS for GoDAM Video Block

- pages/godam/components/GoDAMFooter.jsx
This PR adds `aria-labels` to social icons as discernible text for screen readers.
Closes #425
> fix: add aria labels to social icons as discernible text for screen readers.

- pages/video-editor/components/appearance/Appearance.js
This PR fixes the fix: correct casing of play button position name in select control.
1. Before
2. After
Closes #421
> fix: correct casing of play button position name in select control

- pages/video-editor/components/appearance/Appearance.js
This PR shows `Replace` and `Remove` buttons for `Custom Brand Logo` and `Custom Play Button` only when an image is selected.
[Uploading Kazam_screencast_00007.webm…]()
> fix: show Replace and Remove buttons only when a custom logo or play button image is selected

- assets/src/js/elementor/frontend.js
- assets/src/js/elementor/widgets/godam-video.js
- inc/classes/class-elementor-widgets.php
- inc/classes/elementor-widgets/class-godam-video.php
This PR updates the name of GoDAM Player to GoDAM Video, non breaking change.
> Fix: Updates GoDAM Player name to GoDAM Video for Elementor

- pages/video-editor/VideoEditor.js
- pages/video-editor/components/media-grid/MediaItem.jsx
- pages/video-editor/style.scss
- pages/video-editor/utils/index.js
This PR adds update to copy the `GoDAM Video` block to clipboard from the Video Editor page.
Ref:
https://github.com/user-attachments/assets/3a0d3ee9-a9db-4153-8433-87962206cf96
> FEAT: Add functionality to copy GoDAM Video block

- assets/src/blocks/godam-player/edit-common-settings.js
- Most browser does not allow autoplay of videos if they are unmuted.
- Therefore, in the video block autoplay is automatically disable if the video is unmuted.
- An appropriate help message is also shown, instructing the user to mute the video first.
https://github.com/user-attachments/assets/fe8c66f7-c0f8-4267-bc22-9f1958c1ec07
- #547
> GH-547 feat: Show Description for Autoplay Video Block

- pages/video-editor/components/media-grid/MediaGrid.jsx
- If we navigate to VideoEditor Page open a video, the Admin dashboard main sidebar will be automatically collapsed, but if we go back using the browser back button to the VideoEditor page it will remain collapsed.
- Ideally it should reopen, so that state is conserved.
- Once VideoEditor page is loaded, we will check if the sidebar is still closed by the `folded` class introduced by us. If it's present we can safely remove it from the body tag.
Before
https://github.com/user-attachments/assets/70d28173-a556-46ad-b573-7a958de0ef18
After
https://github.com/user-attachments/assets/5c62dd27-d9ca-46e5-9d22-4de9eccefbca
- #506
> Fix: Open admin sidebar on VideoEditor page

- pages/video-editor/components/SidebarLayers.js
**Issue:** Ads, Polls, and WooCommerce layer are showing warning message on video editor, even if related plugins are active
> Fix video editor warnings

- inc/classes/class-pages.php
* fix: disable rendering of antispam fields in the video editor page for wpforms
* fix: phpcs errrors
* fix: typo
* reset global  godam current request variable
* remove vscode configuration files
> Fix: Rendering of anti-spam fields in the video editor page for wpforms

- assets/src/js/godam-player/frontend.js
- inc/classes/rest-api/class-settings.php
- inc/templates/godam-player.php
- pages/godam/App.js
- pages/godam/components/tabs/AdsSettings/AdsSettings.jsx
- pages/godam/redux/slice/media-settings.js
Provide a global Ads settings section on the GoDAM settings page, which will allow the site owner to add their AdSense URL and apply those specific AdSense Unit Ads to all videos across the site.
https://github.com/user-attachments/assets/1c6c1b14-76da-4690-b184-ae7b708f92e9
https://github.com/user-attachments/assets/1cc09024-cf29-4ba9-a83d-ca84d353174d
Sample **AdTag URL** to test the feature: https://googleads.g.doubleclick.net/pagead/ads?ad_type=video_text_image&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=30000&adtest=on
Closes: https://github.com/rtCamp/godam-core/issues/202
> Implement Global Ads settings

- assets/src/js/godam-recorder/index.js
> GH 628: Fix uppy object to enforce max file size restrictions

- inc/classes/class-media-library-ajax.php
closes #625 
Add error handling when making request from GoDAM tab in the Block editor
> fix: add error handling when fetching media library GoDAM tab data

- admin/class-rtgodam-transcoder-handler.php
Closes #621 
Added a check in `wp_media_transcoding` function which returns early if the IP address is a blacklisted IP address.
When media files are uploaded from the local development environment, a request is automatically sent to GoDAM Core to transcode the media. However, since the media is stored locally, Frappe is unable to download the file for processing. As a result:
- The transcoding process fails silently or stalls.
- Frappe is unable to send status updates back to GoDAM Plugin.
- Unnecessary entries are created in the Frappe app related to transcoding, which leads to clutter and potential confusion.
When adding a media, the transcoding does not happen and the request is not made.
When adding a media, transcoding is done as expected.
Initially I tried returning an `WP_Error` …
> Fix: Prevent Block transcoding on localhost and blacklisted IPs

- pages/video-editor/components/media-grid/MediaGrid.jsx
This PR addresses a race condition that caused duplicate or incorrect video attachments to appear in the media grid when users rapidly changed the search input.
When multiple asynchronous fetch requests are triggered quickly (e.g., typing 2025, then backspacing to 202, 20, etc.), older responses may resolve after newer ones and incorrectly update the attachments state. This led to duplicated or outdated results being rendered.
- Open the `Video Editor` sub-settings in `GoDAM` Settings.
- Open Chrome DevTools → Network tab → Throttle → 3G.
- In the search input, type:
- 2025 ( Or any other substring present in the `Videos Title` in your library )
- Then quickly backspace to 202
- Then re-type 2025 or any variation rapidly
- Observe the media grid:
- Duplicate attachments appear.
- …
> Prevent duplicate attachments on rapid search input

- assets/src/js/media-library/views/attachment-browser.js
closes #669 
This PR removes the Toggle folder sidebar button from rendering for the uploads page.
Before:
After:
> Fix: Upload page hide folder button

- inc/classes/rest-api/class-media-library.php
- pages/media-library/App.js
- pages/media-library/index.scss
- pages/media-library/redux/api/folders.js
This PR adds support for media counts to the All media and Uncategorized button in the media library topbar
> Fix: Topbar add media counts support

- assets/src/css/admin.scss
- assets/src/js/media-library/views/attachment-list.js
- assets/src/js/media-library/views/attachment.js
- pages/media-library/App.js
- pages/media-library/components/context-menu/ContextMenu.jsx
- pages/media-library/components/folder-tree/FolderTree.jsx
- pages/media-library/components/folder-tree/LockedTab.jsx
- pages/media-library/redux/slice/folders.js
This PR fixes the following UI bugs
> Fix: Media library locked drag drop

- inc/classes/class-video-permalinks.php
- inc/classes/post-types/class-godam-video.php
Follows up on #630 
This PR adds user settings for controlling CPT pages visibility
New settings are added under Permalinks for controlling whether archive/single pages for videos are visible to public
After introduction of CPTs, the archive & single pages were visible by default
While this may work for websites like YouTube / Netflix, this behavior might not be ideal for other websites which use GoDAM just for hosting & serving their video content in their post
- Two new options: `rtgodam_video_post_allow_archive` & `rtgodam_video_post_allow_single` are added to store user preferences
- Based on these settings, `exclude_from_search` & `has_archive` options are controlled during CPT registration
- `public` & `publicly_queryable` are always set to `true` to allow compatibility with Query …
> Add user settings for CPT visibility in links

- assets/src/css/godam-player.scss
- assets/src/css/pills-skin.scss
- pages/analytics/Analytics.js
1. Always show share button on <768px devices
2. Fix input width in share modal
Issue:
Fix:
3. Fix branding logo style In pills skin so it doesn't overlay on the control bar border radius
Issue:
Fixed:
4. Fix portrait videos overflow in analytics page
Issue: https://godam-develop.rt.gw/wp-admin/admin.php?page=rtgodam_analytics&id=1305
Fixed:
> Fixes to share button and share modal

- inc/helpers/custom-functions.php
Update `!empty` to `isset`, to allow for 0 values in used bandwidth and storage.
1. Before:
3. After:
> fix: Allow 0 values in bandwidth and storage

- admin/class-rtgodam-transcoder-rest-routes.php
- admin/godam-transcoder-actions.php
- admin/godam-transcoder-functions.php
- assets/src/blocks/godam-player/edit.js
- inc/classes/rest-api/class-dynamic-shortcode.php
- inc/classes/rest-api/class-meta-rest-fields.php
- inc/templates/godam-player.php
This PR saves HLS transcodes URL along with the MPD URL. The Video and Gallery block has been updated to construct a video tag with three URLs in the following order
1. MPD
2. HLS
3. Original URL
1. Upload a new video through `WP Media Library`.
2. Once the video is transcoded, verify the HLS URL is saved along with the MPD.
3. Include the video in both the `GoDAM Video` and `GoDAM Gallery` block.
4. Inspect element and verify it has both the three URLS MPD -> HLS -> Origin.
5. Verify on the iPhone, that the HLS URL is being used rather then origin URL
Closes - #618
> enhance: save and use hsl url along with mpd url for transcoded videos.

- webpack.config.js
Closes #732  
Added this in webpack.config.js for build folder:
```js
// Only generate source maps in development mode
devtool: isProduction ? false : 'source-map',
```
So that `.min.js.map` files are not created in production.
Previously they were leading to this error:
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 10485760 bytes) in phar:///opt/homebrew/Cellar/wp-cli/2.12.0/bin/wp/vendor/mck89/peast/lib/Peast/Syntax/CommentsRegistry.php on line 170
```
> Fix: GH - #732 - Only generate source maps in development mode

- inc/classes/cron-jobs/class-retranscode-failed-media.php
This PR fixes the cron schedule interval added for retrying failed media transcoding. It was intended to be 10 minutes but values passed to `cron_schedules` was 10 seconds.
> Fix: retranscode_failed_media interval value

- inc/classes/class-video-permalinks.php
- inc/classes/post-types/class-godam-video.php
Closes #718 
This PR merges CPT related settings to a single option
Currently in the plugin, there are 2 CPT related options
1. `rtgodam_video_slug` - Stores the slug for video pages
2. `rtgodam_video_post_settings` - Stores CPT page visiblility settings (array)
It will be better to combine these two into a single option
https://github.com/rtCamp/godam/pull/696#issuecomment-3089400484
- This PR adds another key `video_slug` to the array of `rtgodam_video_post_settings` that stores the value of CPT rewrite slug
- For existing users, the behavior is as follows:
- If `rtgodam_video_slug` is set in DB, it'll  continue to be used
- When the user updates permalink settings, value from `rtgodam_video_slug` will be merged into `rtgodam_video_post_settings` & the old option will be deleted
> Enhancement: merge CPT settings into a single option

- pages/godam/components/tabs/VideoSettings/APISettings.jsx
- pages/godam/components/tabs/VideoSettings/components/PasswordFieldWIthToggle/index.jsx
- pages/godam/components/tabs/VideoSettings/components/PasswordFieldWIthToggle/style.scss
Issue - https://github.com/rtCamp/godam/issues/766
This PR implements a secure password field component with toggle visibility functionality for API key input, enhancing user experience while maintaining security best practices.
**Enhanced API Key Input Field**
- Added eye icon toggle to show/hide API key during input
- Conditional rendering based on API key validation state
- Uses WordPress native seen/unseen icons for consistency
- Includes proper accessibility labels for screen readers
User Experience: API keys are typically long, complex strings that are difficult to verify when masked. The toggle allows users to:
- Verify they've entered the correct API key
- Copy-paste keys without guesswork
https://github.com/user-attachments/assets/2b82f095-f398-4afe-9c8e-0540a56dc707
> Add API hide and show toggle with eye icon

- assets/src/css/godam-player.scss
part of #657 
Fix Video Block container in Form Entry view to show correct aspect ratio for the video.
| Before | After |
| --- | --- |
| <img width="661" height="759" alt="image" src="https://github.com/user-attachments/assets/d5ec242c-9d27-45ef-bbd3-13a13abf6e88" /> | <img width="690" height="715" alt="image" src="https://github.com/user-attachments/assets/44e5f0a6-8a05-47bd-a2c8-9b8816dbe633" /> |
> Fix: Video block aspect ratio in forms

- assets/src/css/admin.scss
- assets/src/js/media-library/models/attachments.js
- assets/src/js/media-library/views/filters/media-date-range-filter-list-view.js
- assets/src/js/media-library/views/filters/media-date-range-filter.js
This PR improves the handling of the Media Date Range Filter in both the UI and JavaScript logic.
- Hides the date range filter from the GoDAM library interface.
- Removed unused query param `date_query` from the `GODAMAttachmentCollection` model.
- Ensured date inputs are readonly to prevent manual typing in both List and Default filter views.
> Make date range filter input readonly to prevent manual typing

- admin/godam-transcoder-actions.php
Details
- Issue: #822 
- Show HLS URL field only for videos.
> Fix: Show HLS CDN URL only for video

- inc/templates/godam-player.php
Issue – https://github.com/rtCamp/godam/issues/812
This PR resolves the issue for the Volume Panel Slider not being respected for the GoDAM player.
> Fix disable inline volume panel for Minimal and Pills player skins

- assets/src/js/godam-player/masterSettings.js
- Issue #855 
- Removed global variables and assigned `selectedSpeed` and `selectedQuality` as properties on the player instance.
- Removed DOM loop that applied playback rate across all video instances
https://github.com/user-attachments/assets/b28a932e-b6bf-4737-9e91-b6220cebad96
> Fix: Ensure video speed and quality settings are player-specific

- assets/src/css/admin.scss
- inc/classes/class-pages.php
- pages/analytics/Analytics.js
- pages/analytics/index.scss
- pages/dashboard/index.scss
- pages/godam/components/godam-footer.scss
- pages/godam/index.scss
- pages/help/index.scss
- pages/style.css
- pages/tools/index.scss
- pages/video-editor/AttachmentPicker.jsx
- pages/video-editor/VideoEditor.js
- pages/video-editor/style.scss
- Fix the GoDAM admin pages UI and negative margin.
- Fix the single video analytics heatmap layout break.
- Fix the GoDAM theme colors issue.
- Remove redudant CSS.
#886 #885
> Fix the negative margin issue, and refactor the godam admin page UI

- assets/src/css/admin.scss
> Fix the godam admin page theme style

- inc/classes/rest-api/class-video-migration.php
This PR removes this decimal precision from migration % text:
Only whole numbers will now be visible.
cc: @subodhr258
> Fix: migration percentage decimal

- inc/classes/elementor-widgets/class-godam-video.php
**Issue**: https://github.com/rtCamp/godam/issues/821
Added a bunch of new player skins (`godam-player-minimal-skin`, `godam-player-pills-skin`, `godam-player-bubble-skin`, `godam-player-classic-skin`) to the `depended_styles` list in `class-godam-video.php`.
This makes sure the Elementor widget has these extra skin options ready to use out of the box.
Note: This follows the same approach we already use for enqueuing assets in the Gutenberg block.
> Player skin not applying for videos added through Elementor

- assets/src/css/admin.scss
- assets/src/js/media-library/index.js
ISSUE: https://github.com/rtCamp/godam/issues/826#issuecomment-3200209874
When .hide-sidebar is applied → hide .media-frame-menu & .media-frame-menu-heading
> Fix overlap Issue for media library

- godam.php
Issue - #409 
This PR fixes an issue where the What’s New page was not redirected after deleting and reinstalling the GoDAM plugin.
Changes made:
- Removed What's New page related options on plugin deletion.
- Ensures that a new installation is treated as a fresh install, triggering the redirect.
> Fix: Redirect to What's New Page after reinstalling GoDAM plugin

- godam.php
- inc/classes/class-pages.php
- pages/whats-new/components/Features.js
This PR fixes the following:
- Multisite Handling ([ref](https://github.com/rtCamp/godam/pull/956#discussion_r2292999097)):
- Ensured plugin options and transients are correctly handled for both network-activated and site-specific activations.
- For network-activated plugins, data is cleared across all sites and for site-specific, only on the current site.
- WP Script PHP notice ([ref](https://github.com/rtCamp/godam/issues/409#issuecomment-3223154144)):
- Fixed warning by passing an array to `wp_localize_script()` instead of a direct variable.
> Fix multisite handling and script localization warning

- assets/src/css/classic-skin.scss
- assets/src/css/godam-player.scss
- assets/src/css/pills-skin.scss
- assets/src/images/classic-exit-full-screen.svg
- assets/src/images/close.svg
- assets/src/js/godam-player/managers/controlsManager.js
On iOS devices, the GoDAM video player cannot enter fullscreen mode using the default Video.js option. This causes the video to appear blank without layers, ads, or the GoDAM player skin.
Ref: https://github.com/rtCamp/godam-core/issues/124
**Solution:**
Detect if the user is on iOS, then replace the default Video.js fullscreen button with a custom one. The custom button will handle full-screen behavior manually, allowing us to simulate fullscreen mode on iOS without triggering the native video player.
**Before**
iOS default video player
**After**
| Mimic fullscreen | with layers | Classic skin |
|----------|----------|----------|
| ![WhatsApp Image 2025-08-27 at 18 06 32](https://github.com/user-attachments/assets/9964dc48-e436-4a59-b2cf-0f197071eb16) | ![WhatsApp Image 2025-08-27 at 18 …
> Implement custom fullscreen feature for iOS devices

- assets/src/js/media-library/views/attachment-detail-two-column.js
part of https://github.com/rtCamp/godam-core/issues/359
Fix infinite thumbnail loading issue when thumbnails are not available, show a message when no thumbnails found message
> Fix: Thumbnail infinite loading spinner

- inc/classes/rest-api/class-video-migration.php
This pull request updates how video thumbnails are handled when creating attachments from Vimeo videos. Instead of saving just a single thumbnail URL, the code now supports multiple thumbnails and marks the active one as primary.
**Improvements to thumbnail handling:**
- Modified the logic in create_attachment_from_vimeo_video (in class-video-migration.php) to support multiple thumbnails: now saves all available thumbnail URLs in the rtgodam_media_thumbnails post meta and sets the primary thumbnail based on the is_active flag in the thumbnail data.
> Provide thumbnail support for vimeo video migration

- assets/src/js/godam-player/videoPlayer.js
This pull request refactors the initialization sequence of the ads manager within the `GodamVideoPlayer` class to ensure that ad integration is set up earlier in the player lifecycle. The changes primarily reorganize where and when the ads manager is instantiated and its integration is initialized.
Initialization sequence improvements:
* Moved the instantiation and setup of the `AdsManager` from later in the constructor to the `initializePlayer()` method, ensuring ad integration (`setupAdsIntegration()`) occurs immediately after the player is created. [[1]](diffhunk://#diff-9de8b1ceb38dc381f89c07ae025567054ac8a66fff887ec1374f6ef244542398R68-R72) [[2]](diffhunk://#diff-9de8b1ceb38dc381f89c07ae025567054ac8a66fff887ec1374f6ef244542398L138-L140)
* Removed the redundant call to …
> Modify the admanager initialization order

- assets/src/blocks/godam-player/block.json
- inc/classes/rest-api/class-video-migration.php
- pages/tools/components/tabs/Migration/VimeoVideoMigration.jsx
Before:
After:
https://github.com/user-attachments/assets/e67eb949-f0d3-4014-aad1-407096bd0546
> Vimeo Migration Hotfixes

- inc/classes/rest-api/class-transcoding.php
- pages/tools/components/tabs/RetranscodeTab.jsx
> fix: Avoid re-transcoding virtual media and Vimeo videos

- assets/src/js/jetpack-form.js
Related Issue: https://github.com/rtCamp/godam/issues/873
Remove the `jetpack_contact_form_jwt` from the form fields when submitting the form to prevent the fields from shifting in the form entry.
https://github.com/user-attachments/assets/4e17176e-4353-48dc-8f6d-550b59d93667
https://github.com/user-attachments/assets/e82c150b-4f78-4e6b-92ec-4c6bf26c3fea
> Fix: Jetpack Form Entry

- assets/src/blocks/godam-player/edit.js
- inc/templates/godam-player.php
Update the video sources sequence for the GoDAM video player to fix the Audio mute issue on the Safari browser.
**Old sequence**
- MPD source
- HLS source
- Original File source
**New sequence**
- HLS source
- MPD source
- Original File source
`MPD` format isn’t fully supported on Safari for Mac, which causes the audio to mute after a few seconds. To resolve this, we should prioritize the `HLS` format, as it is well supported across Mac browsers and devices.
- Update the source sequence in the GoDAM Video block edit page
- Update the frontend video source sequence in the GoDAM Video block and shortcode
- Fix the edge case of virtual media source sequence to avoid future bus and take care for the existing virtual media audio issue.
- Provide `hls_transcoded_url` attribute support for …
> Fix the audio mute issue on mac safari browser for GoDAM video block

- .github/workflows/release_on_tag.yml
This pull request updates the release workflow to ensure the plugin ZIP artifact is properly structured for WordPress installation before being uploaded or released. The main change is the introduction of a repacking step to re-zip the plugin files, and updating the upload steps to use the new ZIP file.
**Artifact packaging improvements:**
* Added a "Repack Artifact" step to extract the original plugin ZIP, repackage its contents into a new ZIP (`godam.zip`), and make it available for subsequent upload steps.
**Artifact upload adjustments:**
* Updated both the "Upload Test Artifact" and "Upload Release Artifact" steps to use the new `godam.zip` file instead of the original ZIP path, ensuring the uploaded artifact is correctly structured for WordPress installation.
> Add repackaging step for WordPress plugin ZIP

- assets/src/js/godam-player/managers/configurationManager.js
- inc/templates/godam-player.php
This pull request introduces a new method for prioritizing video sources based on the user's browser and device, specifically optimizing playback for Safari and iOS users. The main change is the addition of logic to rearrange the order of video sources so that the most compatible format is selected first, enhancing the user experience and reducing playback issues.
**Video source prioritization improvements:**
* Added a new method `rearrangeVideoSources` to `ConfigurationManager` that detects Safari and iOS browsers and orders video sources (`.m3u8`, `.mpd`, and normal formats) to prioritize compatibility for those platforms.
* Updated the initialization logic in `ConfigurationManager` to use the rearranged video sources when setting up video controls, ensuring the preferred formats are …
> Fix videojs console errors

- assets/src/js/jetpack-form.js
Related issue: https://github.com/rtCamp/godam/issues/1174
In Jetpack v14.9 and above, the Interactivity API is used to manage forms. When a Jetpack form is used inside a GoDAM video block, console errors related to field registration are thrown. This happens because the entire form is being replaced on the frontend, causing the Interactivity API scripts to initialize twice.
Added a check to replace the from only if the form is using it is using ajax form submission.
**Before**
**After**
> Fix: Jetpack Form console error

- assets/src/js/godam-player/managers/eventsManager.js
- assets/src/js/godam-player/videoPlayer.js
Quality selector on transcoded video was not working consistently, it would not always show up. Sometimes visible upon hard refresh `Ctrl/Cmd + Shift + R`
It would work with preload set to `none`
- Upon player loading adding force check to load quality controls.
- If data preloads before player, player will load again to check if quality levels are available and show the selector.
Before:
https://github.com/user-attachments/assets/d6cdf393-28ad-4ebb-a3be-0857ca45ada3
After: 
https://github.com/user-attachments/assets/c3d14d26-dac0-49d4-b9ac-041bda6e0eb3
- #1141
> FIX: Make quality selector work consistently

- admin/class-rtgodam-transcoder-handler.php
- admin/godam-transcoder-functions.php
- inc/classes/class-media-library-ajax.php
- inc/classes/rest-api/class-transcoding.php
- inc/helpers/custom-functions.php
- pages/tools/components/tabs/RetranscodeTab.jsx
The primary change is the introduction of a new helper function to identify local environments, which is then utilized to bypass media upload and transcoding requests when developing locally.
**Local environment detection and conditional logic:**
* Added the new helper function `rtgodam_is_local_environment()` in `inc/helpers/custom-functions.php` to check if the site is running in a local development environment based on IP, host, or a constant.
* Updated `send_transcoding_request()` in `admin/class-rtgodam-transcoder-handler.php` to return early if running locally, preventing unnecessary transcoding requests during development.
* Updated `upload_media_to_frappe_backend()` in `inc/classes/class-media-library-ajax.php` to return early if running locally, preventing media uploads to the …
> Add rtgodam_is_local_environment function and restrict the media transcoding for local environment

- assets/src/blocks/godam-player/edit.js
- assets/src/js/media-library/utility.js
- assets/src/js/media-library/views/attachment-detail-two-column.js
- assets/src/js/media-library/views/filters/media-retranscode.js
- inc/classes/class-assets.php
- inc/classes/class-pages.php
- inc/classes/rest-api/class-video-migration.php
- pages/video-editor/attachment-picker.scss
- FIX: `Retranscode Media` button was made hidden from editor role, now visible.
- FEAT: Author user can only see analytics of his added media only
- FEAT: User who don't have access to the manage attachment will not see the `Customise Video` button on the block editor
- FIX: Tools page is now visible to editor
| Issue                                | Before   | After        |
|--------------------------------------|----------|--------------|
| Retranscode button visible to editor |  | <img width="548" height="230" alt="Screenshot 2025-10-07 at 9 00 09 PM" src="https://github.com/user-attachments/assets/bba7f5bc-7aca-48fb-a924-60506e3eacb3" /> |
| Author can see own media analytics only (User can see edit video button for own media, and analytics button for all media) |  <img width="478" …
> Refactor the GoDAM pages permission for core users roles
